image: python:3.7-stretch

before_script:
  - pip3 install --upgrade pip
  - pip3 install -r requirements.txt .
  - git clone https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.com:alexgorji/py_musicxml.git

build:
  script:
    - nosetests
