image: python:3.7-stretch

before_script:
  - git config --global url."https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.com/alexgorji/music_score.git"
  - pip3 install --upgrade pip
  - pip3 install -r requirements.txt .


build:
  script:
    - nosetests
